//! Challenge-response authentication for UncrownedKing.

use std::{
    collections::HashMap,
    time::{Duration, SystemTime, UNIX_EPOCH},
};

use hmac::{Hmac, Mac};
use rand::RngCore;
use sha2::Sha256;
use thiserror::Error;

type HmacSha256 = Hmac<Sha256>;

const AUTH_LABEL: &[u8] = b"UK-AUTH-v1";

/// Authentication result alias.
pub type AuthResult<T> = Result<T, AuthError>;

/// Authentication failures.
#[derive(Debug, Error, Clone, PartialEq, Eq)]
pub enum AuthError {
    /// The supplied key id does not exist.
    #[error("unknown key")]
    UnknownKey,
    /// The credential is not active for the current time.
    #[error("credential is not active")]
    CredentialNotActive,
    /// The supplied tag does not match.
    #[error("invalid hmac tag")]
    InvalidTag,
    /// The client timestamp is outside the allowed skew.
    #[error("client timestamp outside allowed skew")]
    ClockSkew,
    /// The nonce pair has already been accepted.
    #[error("replayed nonce")]
    Replay,
    /// Secret material is too short.
    #[error("secret must be at least 32 bytes")]
    SecretTooShort,
}

/// Credential lifecycle state.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CredentialStatus {
    /// May authenticate.
    Active,
    /// Temporarily disabled.
    Disabled,
    /// Permanently retired.
    Retired,
}

/// Server-side credential record.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Credential {
    /// Opaque key id sent by the client.
    pub key_id: Vec<u8>,
    /// Shared secret, at least 32 bytes.
    pub secret: Vec<u8>,
    /// Lifecycle status.
    pub status: CredentialStatus,
    /// Optional unix timestamp when the key becomes valid.
    pub not_before: Option<u64>,
    /// Optional unix timestamp when the key stops being valid.
    pub not_after: Option<u64>,
    /// Optional policy group name.
    pub policy_group: Option<String>,
}

impl Credential {
    /// Creates an active credential with no validity window.
    pub fn active(key_id: impl Into<Vec<u8>>, secret: impl Into<Vec<u8>>) -> AuthResult<Self> {
        let credential = Self {
            key_id: key_id.into(),
            secret: secret.into(),
            status: CredentialStatus::Active,
            not_before: None,
            not_after: None,
            policy_group: None,
        };
        credential.validate_secret()?;
        Ok(credential)
    }

    fn validate_secret(&self) -> AuthResult<()> {
        if self.secret.len() < 32 {
            Err(AuthError::SecretTooShort)
        } else {
            Ok(())
        }
    }

    fn is_active_at(&self, now: u64) -> bool {
        if self.status != CredentialStatus::Active {
            return false;
        }
        if self.not_before.is_some_and(|not_before| now < not_before) {
            return false;
        }
        if self.not_after.is_some_and(|not_after| now > not_after) {
            return false;
        }
        true
    }
}

/// Server challenge payload data.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AuthChallenge {
    /// 32 bytes generated by the server.
    pub server_nonce: [u8; 32],
    /// Server unix time in seconds.
    pub server_time: u64,
    /// Opaque 16-byte session id.
    pub session_id: [u8; 16],
    /// Server capability bytes.
    pub server_capabilities: Vec<u8>,
    /// Server limit bytes.
    pub limits: Vec<u8>,
}

impl AuthChallenge {
    /// Generates a fresh challenge for `now`.
    pub fn generate(now: u64) -> Self {
        let mut server_nonce = [0_u8; 32];
        let mut session_id = [0_u8; 16];
        rand::thread_rng().fill_bytes(&mut server_nonce);
        rand::thread_rng().fill_bytes(&mut session_id);
        Self {
            server_nonce,
            server_time: now,
            session_id,
            server_capabilities: Vec::new(),
            limits: Vec::new(),
        }
    }
}

/// Client authentication response data.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AuthResponse {
    /// Opaque key id.
    pub key_id: Vec<u8>,
    /// 32 bytes generated by the client.
    pub client_nonce: [u8; 32],
    /// Client unix time in seconds.
    pub client_time: u64,
    /// Client capability bytes.
    pub client_capabilities: Vec<u8>,
    /// 32-byte HMAC tag.
    pub tag: [u8; 32],
}

/// In-memory replay cache for accepted nonce pairs.
#[derive(Debug, Clone)]
pub struct ReplayCache {
    window: Duration,
    entries: HashMap<ReplayKey, u64>,
}

impl ReplayCache {
    /// Creates a cache retaining accepted nonces for `window`.
    pub fn new(window: Duration) -> Self {
        Self {
            window,
            entries: HashMap::new(),
        }
    }

    /// Records a nonce pair or rejects it if it was already seen.
    pub fn check_and_insert(
        &mut self,
        now: u64,
        server_nonce: [u8; 32],
        client_nonce: [u8; 32],
    ) -> AuthResult<()> {
        self.prune(now);
        let key = ReplayKey {
            server_nonce,
            client_nonce,
        };
        if self.entries.contains_key(&key) {
            return Err(AuthError::Replay);
        }
        self.entries.insert(key, now);
        Ok(())
    }

    fn prune(&mut self, now: u64) {
        let window = self.window.as_secs();
        self.entries
            .retain(|_, inserted_at| now.saturating_sub(*inserted_at) <= window);
    }
}

impl Default for ReplayCache {
    fn default() -> Self {
        Self::new(Duration::from_secs(300))
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
struct ReplayKey {
    server_nonce: [u8; 32],
    client_nonce: [u8; 32],
}

/// Computes the v0.1 authentication HMAC tag.
pub fn compute_auth_tag(
    secret: &[u8],
    exporter_32: &[u8; 32],
    challenge: &AuthChallenge,
    key_id: &[u8],
    client_nonce: &[u8; 32],
    client_time: u64,
    client_capabilities: &[u8],
) -> AuthResult<[u8; 32]> {
    let mac = auth_mac(
        secret,
        exporter_32,
        challenge,
        key_id,
        client_nonce,
        client_time,
        client_capabilities,
    )?;
    let bytes = mac.finalize().into_bytes();
    Ok(bytes.into())
}

/// Verifies an authentication response and records the nonce pair in the replay cache.
pub fn verify_auth_response(
    credentials: &[Credential],
    exporter_32: &[u8; 32],
    challenge: &AuthChallenge,
    response: &AuthResponse,
    now: u64,
    allowed_skew: Duration,
    replay_cache: &mut ReplayCache,
) -> AuthResult<Credential> {
    let credential = credentials
        .iter()
        .find(|credential| credential.key_id == response.key_id)
        .ok_or(AuthError::UnknownKey)?;
    credential.validate_secret()?;

    if !credential.is_active_at(now) {
        return Err(AuthError::CredentialNotActive);
    }

    let skew = now.abs_diff(response.client_time);
    if skew > allowed_skew.as_secs() {
        return Err(AuthError::ClockSkew);
    }

    auth_mac(
        &credential.secret,
        exporter_32,
        challenge,
        &response.key_id,
        &response.client_nonce,
        response.client_time,
        &response.client_capabilities,
    )?
    .verify_slice(&response.tag)
    .map_err(|_| AuthError::InvalidTag)?;

    replay_cache.check_and_insert(now, challenge.server_nonce, response.client_nonce)?;
    Ok(credential.clone())
}

fn auth_mac(
    secret: &[u8],
    exporter_32: &[u8; 32],
    challenge: &AuthChallenge,
    key_id: &[u8],
    client_nonce: &[u8; 32],
    client_time: u64,
    client_capabilities: &[u8],
) -> AuthResult<HmacSha256> {
    if secret.len() < 32 {
        return Err(AuthError::SecretTooShort);
    }
    let mut mac = HmacSha256::new_from_slice(secret).map_err(|_| AuthError::SecretTooShort)?;
    mac.update(AUTH_LABEL);
    mac.update(exporter_32);
    mac.update(&challenge.server_nonce);
    mac.update(client_nonce);
    mac.update(&challenge.session_id);
    mac.update(key_id);
    mac.update(&client_time.to_be_bytes());
    mac.update(client_capabilities);
    Ok(mac)
}

/// Returns the current unix time in seconds.
pub fn unix_now() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_or(0, |duration| duration.as_secs())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture() -> (Credential, [u8; 32], AuthChallenge, AuthResponse) {
        let credential = Credential::active(
            b"client-a".to_vec(),
            b"0123456789abcdef0123456789abcdef".to_vec(),
        )
        .unwrap();
        let exporter = [0x11; 32];
        let challenge = AuthChallenge {
            server_nonce: [0x22; 32],
            server_time: 1_700_000_000,
            session_id: [0x33; 16],
            server_capabilities: vec![1, 2, 3],
            limits: vec![4, 5, 6],
        };
        let client_nonce = [0x44; 32];
        let client_time = 1_700_000_001;
        let tag = compute_auth_tag(
            &credential.secret,
            &exporter,
            &challenge,
            &credential.key_id,
            &client_nonce,
            client_time,
            b"cap",
        )
        .unwrap();
        let response = AuthResponse {
            key_id: credential.key_id.clone(),
            client_nonce,
            client_time,
            client_capabilities: b"cap".to_vec(),
            tag,
        };
        (credential, exporter, challenge, response)
    }

    #[test]
    fn accepts_valid_auth() {
        let (credential, exporter, challenge, response) = fixture();
        let mut replay_cache = ReplayCache::default();
        let verified = verify_auth_response(
            &[credential],
            &exporter,
            &challenge,
            &response,
            1_700_000_001,
            Duration::from_secs(30),
            &mut replay_cache,
        )
        .unwrap();
        assert_eq!(verified.key_id, b"client-a");
    }

    #[test]
    fn rejects_unknown_key() {
        let (credential, exporter, challenge, mut response) = fixture();
        response.key_id = b"missing".to_vec();
        let mut replay_cache = ReplayCache::default();
        assert_eq!(
            verify_auth_response(
                &[credential],
                &exporter,
                &challenge,
                &response,
                1_700_000_001,
                Duration::from_secs(30),
                &mut replay_cache
            ),
            Err(AuthError::UnknownKey)
        );
    }

    #[test]
    fn rejects_invalid_hmac() {
        let (credential, exporter, challenge, mut response) = fixture();
        response.tag[0] ^= 0xff;
        let mut replay_cache = ReplayCache::default();
        assert_eq!(
            verify_auth_response(
                &[credential],
                &exporter,
                &challenge,
                &response,
                1_700_000_001,
                Duration::from_secs(30),
                &mut replay_cache
            ),
            Err(AuthError::InvalidTag)
        );
    }

    #[test]
    fn rejects_expired_timestamp() {
        let (credential, exporter, challenge, mut response) = fixture();
        response.client_time = 1_600_000_000;
        response.tag = compute_auth_tag(
            &credential.secret,
            &exporter,
            &challenge,
            &response.key_id,
            &response.client_nonce,
            response.client_time,
            &response.client_capabilities,
        )
        .unwrap();
        let mut replay_cache = ReplayCache::default();
        assert_eq!(
            verify_auth_response(
                &[credential],
                &exporter,
                &challenge,
                &response,
                1_700_000_001,
                Duration::from_secs(30),
                &mut replay_cache
            ),
            Err(AuthError::ClockSkew)
        );
    }

    #[test]
    fn rejects_replayed_nonce() {
        let (credential, exporter, challenge, response) = fixture();
        let mut replay_cache = ReplayCache::default();
        verify_auth_response(
            std::slice::from_ref(&credential),
            &exporter,
            &challenge,
            &response,
            1_700_000_001,
            Duration::from_secs(30),
            &mut replay_cache,
        )
        .unwrap();
        assert_eq!(
            verify_auth_response(
                &[credential],
                &exporter,
                &challenge,
                &response,
                1_700_000_002,
                Duration::from_secs(30),
                &mut replay_cache
            ),
            Err(AuthError::Replay)
        );
    }
}
